/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package multiagentes.jade.ticktacktoe;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ladis
 */
public class Window extends javax.swing.JFrame {
    
    ArrayList<JLabel>   _cells;
    ImageIcon           _cross;
    ImageIcon           _circle;

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        
        _cross = createImageIcon("img/cross.png", "Icon for player 1");
        _circle = createImageIcon("img/circle.png","Icon for player 2");
        
        if(_cross == null) {
            System.out.println("Failed to load cross.png");
            System.out.println("Failed to load circle.png");
        }
        
        _cells = new ArrayList<>(9);
        
        _cells.add(casilla00);
        _cells.add(casilla01);
        _cells.add(casilla02);
        _cells.add(casilla10);
        _cells.add(casilla11);
        _cells.add(casilla12);
        _cells.add(casilla20);
        _cells.add(casilla21);
        _cells.add(casilla22);
        
        // Test
        //_cells.get(0).setIcon(_cross);
    }
    
    /**
     * Adds a new movement.
     * @param pos       Square where movement is added
     * @param player    Movement's owner.   1 = Player1     2 = Player2
     */
    public void addMovement(int pos, int player) {
        if(player == 1) {    // Player 1
            _cells.get(pos).setIcon(_circle);
        }else if(player == 2) { // Player 2
            _cells.get(pos).setIcon(_cross);
        }
    }
    
    public void addMovement(int x, int y, int player) {
        addMovement((x * 3) + y,player);
    }
    
    /**
     * Cleans the board
     */
    public void clear() {
        for(int i = 0; i < _cells.size(); i++) {
            _cells.get(i).setIcon(null);
        }
    }
    
    private ImageIcon createImageIcon(String path, String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jugadoresPanel = new javax.swing.JPanel();
        jugador1Label = new javax.swing.JLabel();
        casillasPanel = new javax.swing.JPanel();
        casilla00 = new javax.swing.JLabel();
        casilla01 = new javax.swing.JLabel();
        casilla02 = new javax.swing.JLabel();
        casilla10 = new javax.swing.JLabel();
        casilla11 = new javax.swing.JLabel();
        casilla12 = new javax.swing.JLabel();
        casilla20 = new javax.swing.JLabel();
        casilla21 = new javax.swing.JLabel();
        casilla22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jugadoresPanel.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        jugadoresPanel.setLayout(new java.awt.GridBagLayout());

        jugador1Label.setText("TIK TAK TOE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 6, 46, 0);
        jugadoresPanel.add(jugador1Label, gridBagConstraints);

        getContentPane().add(jugadoresPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 551, 50));

        casillasPanel.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        casilla00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla00);

        casilla01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla01);

        casilla02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla02);

        casilla10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla10);

        casilla11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla11);

        casilla12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla12);

        casilla20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla20);

        casilla21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla21);

        casilla22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        casilla22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        casillasPanel.add(casilla22);

        getContentPane().add(casillasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 551, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casilla00;
    private javax.swing.JLabel casilla01;
    private javax.swing.JLabel casilla02;
    private javax.swing.JLabel casilla10;
    private javax.swing.JLabel casilla11;
    private javax.swing.JLabel casilla12;
    private javax.swing.JLabel casilla20;
    private javax.swing.JLabel casilla21;
    private javax.swing.JLabel casilla22;
    private javax.swing.JPanel casillasPanel;
    private javax.swing.JLabel jugador1Label;
    private javax.swing.JPanel jugadoresPanel;
    // End of variables declaration//GEN-END:variables
}
